name: Dizi Veri M3u Yapıcı

on:
  workflow_run:
    workflows: ["Fetch TV Shows and Save to File"]  # Ana Domain workflow'u tamamlandığında çalışacak
    types:
      - completed

jobs:
  run_base_url_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v3  # Daha güncel versiyon kullanıyoruz
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Run diziler_m3u.py
        run: |
          python diziler_m3u.py

      # Ana link dosyasını kontrol ediyoruz
      - name: Check if programlar.m3u is updated
        id: check_update
        run: |
          echo "Checking if programlar.m3u was updated:"
          cat programlar.m3u # Dosyanın içeriğini kontrol ediyoruz
          
          OLD_URL=$(cat programlar.m3u)
          NEW_URL=$(python diziler_m3u.py)  # Yeni URL'yi almak için scripti çalıştırıyoruz
          
          if [ "$OLD_URL" == "$NEW_URL" ]; then
            echo "URL güncellemeye gerek yoktur"
            echo "no_update=true" >> $GITHUB_ENV  # URL değişmemişse environment variable set ediyoruz
          else
            echo "URL başarıyla programlar.m3u dosyasına güncellendi"
            echo "no_update=false" >> $GITHUB_ENV  # URL güncellenmişse farklı bir variable set ediyoruz
          fi

      # GitHub Actions'a yapılan değişiklikleri commit ediyoruz
      - name: Commit updated programlar.m3u
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Değişiklik olup olmadığını kontrol et
          git pull origin main  # Güncel değişiklikleri almak için doğru bir kullanım
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add programlar.m3u
            if [ "${{ env.no_update }}" == "true" ]; then
              git commit -m "Domain URL güncellenmeye gerek yoktur"
            else
              git commit -m "Kanallar güncellendi."
            fi
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
