name: Kanal Bulucu

on:
  workflow_run:
    workflows: ["Run Data Script"]  # Ana Domain workflow'u tamamlandığında çalışacak
    types:
      - completed

jobs:
  run_base_url_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v3  # Daha güncel versiyon kullanıyoruz
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
               pip install beautifulsoup4

      - name: Run kanallar.py
        run: |
          python kanallar.py

      # Ana link dosyasını kontrol ediyoruz
      - name: Check if all_countries_channels.txt is updated
        id: check_update
        run: |
          echo "Checking if all_countries_channels.txt was updated:"
          cat all_countries_channels.txt  # Dosyanın içeriğini kontrol ediyoruz
          
          OLD_URL=$(cat all_countries_channels.txt)
          NEW_URL=$(python kanallar.py)  # Yeni URL'yi almak için scripti çalıştırıyoruz
          
          if [ "$OLD_URL" == "$NEW_URL" ]; then
            echo "URL güncellemeye gerek yoktur"
            echo "no_update=true" >> $GITHUB_ENV  # URL değişmemişse environment variable set ediyoruz
          else
            echo "URL başarıyla all_countries_channels.txt dosyasına güncellendi"
            echo "no_update=false" >> $GITHUB_ENV  # URL güncellenmişse farklı bir variable set ediyoruz
          fi

      # GitHub Actions'a yapılan değişiklikleri commit ediyoruz
      - name: Commit updated all_countries_channels.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Değişiklik olup olmadığını kontrol et
          git pull  # Güncel değişiklikleri almak için ekledik
          if git diff --quiet; then
            echo "No changes detected. Skipping commit."
          else
            git add all_countries_channels.txt
            if [ "${{ env.no_update }}" == "true" ]; then
              git commit -m "Domain URL güncellenmeye gerek yoktur"
            else
              git commit -m "Kanallar güncellendi."
            fi
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # txt-to-m3u.yml workflow'unu tetiklemek
      - name: Trigger txt-to-m3u.yml workflow
        if: ${{ success() }}  # Bu adımdan önce başarılı olursa tetiklenir
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/txt-to-m3u.yml/dispatches
